name: dev_deploy

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  docker_build_push_acr:
    name: 'Docker build and push to ACR'
    runs-on: ubuntu-latest
    environment: development
    
    defaults:
      run:
        shell: bash
        
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: 'Build image and push to ACR'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mlab/lapka-backend:${{ github.sha }}
        file: Dockerfile
